name: Build

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v3.2.1)'
        required: true

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_generic
          - i386_pentium-mmx
          - loongarch64_generic
          - mips_mips32
          - mipsel_24kc
          - mipsel_mips32
          - x86_64
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Building packages
        uses: sbwml/openwrt-gh-action-sdk@go1.24
        env:
          ARCH: ${{ matrix.arch }}-openwrt-24.10
          FEEDNAME: packages_ci
          PACKAGES: luci-app-timecontrol
          NO_REFRESH_CHECK: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    if: success() && (github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''))
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-packages

      - name: Create Release and Upload
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event_name == 'push' && github.ref_name || github.event.inputs.tag }}
          allowUpdates: true
          replacesArtifacts: true
          artifacts: release-packages/**/*.ipk
